# Generated by Django 3.1.7 on 2021-02-22 09:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_auto_20210222_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gchat',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
