# Generated by Django 3.1.7 on 2021-02-23 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_gchat_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gchat',
            name='groups',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.wpgc'),
        ),
    ]
